In [3]:
import torch

In [8]:
import numpy as np


In [15]:
a=torch.rand(2,3)

In [10]:
np.random.rand(3,2)

array([[0.38642855, 0.46214887],
       [0.63160843, 0.34085166],
       [0.6134288 , 0.66999489]])

In [11]:
#Identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
#zero matrix
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
#ones matrix
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
b=torch.rand(3,2)

In [17]:
#matrix multiplication
torch.matmul(a,b)

tensor([[0.6644, 0.7767],
        [0.3539, 0.7515]])

In [20]:
#dot product(same size)
c= torch.rand(3,2)
b*c

tensor([[0.1959, 0.1231],
        [0.1002, 0.0933],
        [0.0828, 0.0458]])

In [23]:
# 1*1 matrix
k = torch.tensor([2])

In [24]:
print(k)

tensor([2])


In [ ]:
# learnt forward propagation through computational graph


In [ ]:
#derivatives: rate of change of a fucntion

In [25]:
x= torch.tensor(-3., requires_grad= True)
y = torch.tensor(5., requires_grad= True)
z= torch.tensor(-2., requires_grad= True)

In [26]:
print(x)
print(y)
print(z)

tensor(-3., requires_grad=True)
tensor(5., requires_grad=True)
tensor(-2., requires_grad=True)


In [27]:
q= x+y
f = q*z

In [28]:
f.backward()

In [29]:
print("gradient of z is: "+str(z.grad))
print("gradient of y is: "+str(y.grad))
print("gradient of x is: "+str(x.grad))

gradient of z is: tensor(2.)
gradient of y is: tensor(-2.)
gradient of x is: tensor(-2.)
